/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bs_indri_v1_Query */

#ifndef _Included_bs_indri_v1_Query
#define _Included_bs_indri_v1_Query
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bs_indri_v1_Query
 * Method:    query_begin
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_bs_indri_v1_Query_query_1begin
  (JNIEnv *, jobject, jobjectArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
